### ISSUE TITLE
Add a .prettierrc with some standard guidelines

### ISSUE THREAD

**Issue by mukarramali** [schmiedeone/vacabot#13]
It doesn't have to be endless.
This repo is to promote new developers mostly. So we need some setup that enforces these rules and reduces the time in PR approvals.
We can have rules like tab size, auto indentations, formatting on save.

**Comment by mariabp** [comment]
I would like to take this issue!

**Comment by Muh-Hasan** [comment]
I would like to take this issue. see this:
`{"useTabs":true,"semi":true,"singleQuote":false,"bracketSpacing":true,"jsxBracketSameLine":true,"arrowParens":"always","filePath":"./","requirePragma":false,"proseWrap":"always"}`

**Comment by mukarramali** [comment]
@mariabp @Muh-Hasan you both can create your own PRs. We can use each other's suggestions. :)
