### ISSUE TITLE
Setup hot reloading

### ISSUE THREAD

**Issue by mukarramali** [schmiedeone/vacabot#4]
Right now every change in code needs a restart of the server.
For hot reloading, you can use any of the solutions available for NodeJS. [Webpack](https://webpack.js.org/configuration/dev-server/) suggested.

**Comment by jasbindar-singh** [comment]
Can install nodemon and setup devScript to run with nodemon

**Comment by mukarramali** [comment]
@jasbindar-singh sounds good. We can assign you to the PR.

**Comment by Bhavesh27** [comment]
@mukarramali i can do the nodemon setup if assigned.

**Comment by jasbindar-singh** [comment]
@Bhavesh27 you can take this :)

**Comment by Bhavesh27** [comment]
@mukarramali https://github.com/schmiedeone/vacabot/pull/18 Added nodemon Config as well if required you can tweak it accordingly.
